service: passwordless-lambda

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}
    MAILGUN_API_KEY: ${self:custom.secrets.MAILGUN_API_KEY}
    MAILGUN_DOMAIN: ${self:custom.secrets.MAILGUN_DOMAIN}

functions:
  login:
    handler: src/handler/User.login
    events:
      - http:
          path: user/login
          method: post
          cors: true

  validate:
    handler: src/handler/User.validate
    events:
      - http:
          path: user/validate
          method: post
          cors: true

plugins:
  - serverless-offline